spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://172.26.211.117:3306/springboot"
    username: naru
    password: naru
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernete.format_sql: true
